---


---

### **Documents**

- Saravia, J. C. (2020). ¿Qué nos enseño Gareca y la selección peruana en su camino hacia el mundial? [Read here](https://medium.com/@jsaraviadrago/qué-nos-enseño-gareca-y-la-selección-peruana-en-su-camino-hacia-el-mundial-c849dc50fe1).[Code here](https://github.com/jsaraviadrago/Mate-posible/tree/master/Data%20eliminatorias%202022/Previa%20Eliminatorias%202022)

- Saravia, J. C. (2020). Un poco de ajedrez en la época el COVID-19. [Read here](https://medium.com/@jsaraviadrago/un-poco-de-ajedrez-en-la-época-del-covid-19-3be353cc9c82).
[Code here](https://github.com/jsaraviadrago/Portafolio/tree/master/6.%20Chess%20predictions%20(2019)) 

- Saravia, J. C. (2017). Evaluating the psychometric properties of the Spanish version of the Family Sense of Coherence scale: How valuable is this measurement for health promotion? [Read here](images/Escalas_FSOC.pdf). [Code here](https://github.com/jsaraviadrago/Portafolio/tree/master/4.%20Family%20Sense%20of%20Coherence%20(2017))

- Saravia, J. C. (2016). Evaluation of the psychometric properties of the SOC-13 scale in Mexico. [Read here](images/SOC_Mexico.pdf). [Code here](https://github.com/jsaraviadrago/Portafolio/tree/master/5.%20SOC%20in%20mexico%20(2016))

- Saravia, J. C (2015). Extending Job hindrance and well being: The mediation effect of mindfulness. [Read here](images/Extending_JH.pdf). [Code here](https://github.com/jsaraviadrago/Portafolio/tree/master/3.%20Job%20hindrance%20(2015))

- Saravia, J. C (2014). How is income distributed between districts by age and job type in Lima Peru. [Read here](images/Income_peru.pdf)

- Saravia, J. C (2014). Propiedades psicométricas de la Escala de Autoestima en escuelas urbanas de Perú. [Read here](images/Escala de Autoestima.pdf). [Code here](https://github.com/jsaraviadrago/Portafolio/tree/master/2.%20Autoestima%20(2014))

- Saravia, J. C. (2013). Factores psicológicos y conductuales de la salud en un grupo de universitarios de Lima Metropolitana. Tesis de Maestría en psicología de la salud. PUCP: Lima. Autor. [Read here](https://www.researchgate.net/publication/275340384_Factores_psicologicos_y_conductuales_de_la_salud_en_un_grupo_de_universitarios_de_Lima_Metropolitana). [Code here](https://github.com/jsaraviadrago/Portafolio/tree/master/1.%20Tesis%20salud%20(2013))

### **Research Papers**

- Seiffge-Krenke I et al, & Saravia, J.C. (2019). Psychopathology in adolescents from seven countries: What role does controlling identity development and family relationships play? Z Kinder Jugendpsychiatr Psychother. 47(5). 441-452. DOI: 10.1024/1422-4917/a000633
- Persike, M et al. & Saravia, J.C. (2018). Emerging Adults’ Psychopathology in Seven Countries: The Impact of Identity-Related Risk Factors. Emerging Adulthood.  1-16
DOI: 10.1177/2167696818791108
- Saravia, J.C.,  & Chau, C. (2017). What factors are related to self – perceived health? The relationship between sense of coherence, behaviors and health on Peruvian emerging adults. 9(2). 111- 116. DOI: https://doi.org/10.1016/j.jbhsi.2017.11.003
- Chau, C., & Saravia, J.C. (2016). How does stress and university adjustment relate to health in Peru? Journal of Behavior, Health & Social Issues 8(1), DOI: http://dx.doi.org/10.5460/jbhsi.v8.1.53089
- Chau, C., & Saravia J. C. (2016). Conductas de salud en estudiantes universitarios limeños: validación del CEVJU. Revista Iberoamericana de Diagnóstico y Evaluación – e Avaliação Psicológica. 41(1) 90-103
- Saravia. J. C., (2015). Why do people trust the government in Peru? Master thesis. Katholieke Universiteit Leuven. Belgium. 
- Chau, C., & Saravia, J. C. (2014). Adaptación Universitaria y su Relación con la Salud Percibida en una Muestra de Jóvenes de Perú. Revista colombiana de psicología. 23(2) 269-284. DOI: 10.15446/rcp.v23n2.41106
- Saravia, J. C., Iberico, C., & Yearwood, K. (2014). Validation of sense of coherence (SOC) 13-item scale in a Peruvian simple. Journal of Behavior, Health & Social Issues 6(2), 34-44. DOI:10.5460/jbhsi.v6.2.43847.
- Saravia, J. C., Gutierrez, C., & Frech, H. (2014). Factores asociados al inicio de consumo de drogas ilícitas en escolares adolescentes.  Revista Peruana de Epidemiología. 18(1) 1-7
- Saravia, J. C., & Frech, H. (2012). Relación entre autoeficacia, autoestima y el consumo de drogas médicas sin prescripción en escolares de colegios urbanos de Perú. (2012) Revista Peruana de Epidemiología. 16(3) 1-7
 - Saravia, J. C., Mejia, M., Becerra, S., & Palomino, A. (2012). Violencia física contra la mujer durante el embarazo: prevalencia y factores asociados. (2012) Revista Peruana de Epidemiología. 16(2) 1-5.
 
To read the articles you can check my [researchgate page](https://www.researchgate.net/profile/Juan_Carlos_Saravia)

### **Papers as part of the Ministry of Education**

- MINEDU. (2018). Desafíos en la medición y el análisis del estatus socioeconómico de los estudiantes peruanos. Lima: Autor. [Read here](http://umc.minedu.gob.pe/desafios-en-la-medicion-y-el-analisis-del-estatus-socioeconomico-de-los-estudiantes-peruanos/)

- MINEDU. (2017). El Perú en PISA 2015. Informe nacional de resultados. Lima: Autor. [Read here](http://umc.minedu.gob.pe/el-peru-en-pisa-2015-informe-nacional-de-resultados/)
    
- MINEDU. (2017). ¿Cómo se relaciona la infraestructura de la escuela con los aprendizajes de los estudiantes? [Read here](http://umc.minedu.gob.pe/como-se-relaciona-la-infraestructura-de-la-escuela-con-los-aprendizajes-de-los-estudiantes/)

- MINEDU. (2016). ¿Influye la ansiedad matemática en la relación entre las oportunidades de aprendizaje y la competencia matemática en estudiantes de 15 años? Lima: Autor. [Read here](http://repositorio.minedu.gob.pe/handle/123456789/4643)

 

